# @package _global_
module:
  _target_: emg2qwerty.lightning.HybridCNNRNNCTCModule
  in_features: 528
  mlp_features: [384]
  # CNN params
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers
  # RNN params
  hidden_size: 256
  num_layers: 3
  dropout: 0.3
  bidirectional: True
  rnn_type: gru # choose from rnn, lstm, gru

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context