# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]


# temporal_subsampling:
#   _target_: emg2qwerty.transforms.TemporalSubsampling
#   stride: 1


band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

frequency_avg:
  _target_: emg2qwerty.transforms.STFTInverseTransform
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    # - ${frequency_avg}

  val:
    - ${to_tensor}
    # - ${frequency_avg}

  test: ${transforms.val}
